name: Deploy to external server
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to external server
    runs-on: ubuntu-latest
    environment: external-env
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: List all files
        run: ls -lR ${{ github.workspace }}
      - name: Clear previous files
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          host_fingerprint: ${{ secrets.EXTERNAL_THUMBPRINT }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          command: rm -rf /var/www/html/test/*
      - name: Copy new files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: ${{ github.workspace }}/*,!${{ github.workspace }}/.github
          target: /var/www/html/test
